[workspace]
members = [
    "src/whisker",
    "src/cutie",
    "src/elfie",
    "src/bitfield",
    "src/bitfield/bitfield_impl",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.29", features = ["derive", "string"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release-with-debug]
inherits = "release"
debug = true
