[package]
name = "whisker"
version = "0.1.0"
edition = "2021"
default-run = "whisker"

[dependencies]
clap.workspace = true
paste = "1.0.15"
gdbstub = "0.7.3"
gdbstub_arch = "0.3.1"

tracing.workspace = true
tracing-subscriber.workspace = true
