[package]
name = "whisker"
version = "0.1.0"
edition = "2021"
default-run = "whisker"

[dependencies]
clap.workspace = true
paste = "1.0.15"
gdbstub = "0.7.3"
gdbstub_arch = "0.3.1"

# has better hash algorithm for basic numbers
rustc-hash = "2.1.1"

softfloat-sys = { git = "https://github.com/whisker-emu/softfloat-sys.git", tag = "v0.2.0", default-features = false, features = [
    "riscv",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
num-conv = "0.1.0"
elfie.path = "../elfie"
bitflags = "2.9.1"
crossterm = "0.29.0"
socketpair = "0.19.8"
command-fds = "0.3.2"
bytemuck = { version = "1.23.1", features = ["derive"] }
